// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview A Genkit flow that extracts student ID information from an ID card image for admin use.
 *
 * - adminExtractBarcodeData - A function that handles the extraction of barcode data.
 * - AdminExtractBarcodeDataInput - The input type for the adminExtractBarcodeData function.
 * - AdminExtractBarcodeDataOutput - The return type for the adminExtractBarcodeData function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const AdminExtractBarcodeDataInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo of a student ID card, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AdminExtractBarcodeDataInput = z.infer<typeof AdminExtractBarcodeDataInputSchema>;

const AdminExtractBarcodeDataOutputSchema = z.object({
  studentId: z.string().describe('The student ID extracted from the barcode image.'),
  studentName: z.string().optional().describe('The name of the student extracted from the ID card, if available.'),
  branch: z.string().optional().describe('The branch of the student extracted from the ID card, if available.'),
  rollNo: z.string().optional().describe('The roll number of the student extracted from the ID card, if available.'),
  yearOfStudy: z.string().optional().describe('The year of study of the student extracted from the ID card, if available.'),
});
export type AdminExtractBarcodeDataOutput = z.infer<typeof AdminExtractBarcodeDataOutputSchema>;

export async function adminExtractBarcodeData(input: AdminExtractBarcodeDataInput): Promise<AdminExtractBarcodeDataOutput> {
  return adminExtractBarcodeDataFlow(input);
}

const adminExtractBarcodeDataPrompt = ai.definePrompt({
  name: 'adminExtractBarcodeDataPrompt',
  input: {
    schema: z.object({
      photoDataUri: z
        .string()
        .describe(
          "A photo of a student ID card, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
        ),
    }),
  },
  output: {
    schema: z.object({
      studentId: z.string().describe('The student ID extracted from the barcode image.'),
      studentName: z.string().optional().describe('The name of the student extracted from the ID card, if available.'),
      branch: z.string().optional().describe('The branch of the student extracted from the ID card, if available.'),
      rollNo: z.string().optional().describe('The roll number of the student extracted from the ID card, if available.'),
      yearOfStudy: z.string().optional().describe('The year of study of the student extracted from the ID card, if available.'),
    }),
  },
  prompt: `You are an expert data extraction specialist.

You will be given an image of a student ID card. Extract the student's ID number from the barcode or the text below the barcode. Also extract the student's name, branch, roll number, and year of study, if available.

Image: {{media url=photoDataUri}}

Output the information in JSON format. If a field is not available, leave it blank. Do not invent information.
`,
});

const adminExtractBarcodeDataFlow = ai.defineFlow<
  typeof AdminExtractBarcodeDataInputSchema,
  typeof AdminExtractBarcodeDataOutputSchema
>(
  {
    name: 'adminExtractBarcodeDataFlow',
    inputSchema: AdminExtractBarcodeDataInputSchema,
    outputSchema: AdminExtractBarcodeDataOutputSchema,
  },
  async input => {
    const {output} = await adminExtractBarcodeDataPrompt(input);
    return output!;
  }
);
